proxies:
- name: ID Nusa 25 08 25
  type: trojan
  server: man4.xmd.asia
  port: 443
  password: Bhpr3uD33lyqvnNTKWjOxA
  udp: true
  sni: live.iflix.com
  skip-cert-verify: true
  network: ws
  ws-opts:
    path: /trojan-ws
  headers:
      Host: man4.xmd.asia
- name: SG LEASwEB 18 08 25
  type: trojan
  server: lwb1.xmd.my.id
  port: 443
  password: KQ3GjQcwaORsYgO5znE4JQ
  udp: true
  sni: live.iflix.com
  skip-cert-verify: true
  network: ws
  ws-opts:
    path: /trojan-ws
  headers:
      Host: lwb1.xmd.my.id
